### ISSUE TITLE
Theme?

### ISSUE THREAD

**Issue by cromwellryan** [cromwellryan/sweetelixir#14]
A place to drop ideas for themes for what they're building as we progress.

**Comment by cromwellryan** [comment]
Stack Server
Chat server
Distributed Map/Reduce (file processing?)

**Comment by chrismccord** [comment]
Distributed map/reduce and actually doing some real CPU flexing would be awesome since we could really showcase distributed computing. Actually getting something to work effectively in practice might prove difficult though. We'd need to do some prep/testing beforehand to make sure the crunching/processing worked well.

Might be silly, but on the simpler side, maybe a distributed tweet aggregator? Basically, we could have one master node that displays tweets on the projector gathered from all the distributed nodes on the network. Attendees would be able to see this work realtime by firing up a node on his/her laptop and tweeting something with a keyword that their node is streaming on from the twitter api. Pseudo-api:

``` elixir
# Process on Master node
defmodule Tweet.Aggregator
  use GenServer.Behaviour
  ...
  def handle_cast({:connect, node_name}, _from, state) do
    IO.puts "#{node_name} connected"
    {:noreply..
  end
  def handle_cast({:tweet, tweet}, _from, state) do
    IO.puts "<#{tweet.node_name}> @#{tweet.username}: #{tweet.content}"
    {:noreply...
  end
end

iex> 
chris-macbook connected
ryan-macbook connected
<chris-macbook> @chrismccord: Sweet Elixir!
<ryan-macbook> @cromwelryan: lorem ipsum




# Process running on distributed nodes (workshop attendees laptops)
iex> Tweet.Client.start(node_name: "chris-macbook", keywords: ["codemash", "elixir"])
Streaming from twitter api on "code mash", "elixir" keywords...
```

Before the workshop, we would have all the Twitter specific details implemented, so the day could be  spent consuming that lib and focusing on the message passing, gen_servers, and processes required to make this happen. There are certainly more practical scenarios, but just a thought. Thoughts?

**Comment by cromwellryan** [comment]
I was able to get 3 others on a distributed setup using the Counter OTP server in 10-otp.  It's a really boring example, but I think we can get a decent enough number of people to get the point across.  It was fun, but .11 screwed up my instructions.

**Comment by cromwellryan** [comment]
Love the tweet aggregator idea btw.
